In [2]:
a = [1.0, 2.0, 3.0]
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### Ejemplo
Representación de coordenadas de los puntos de un triángulo (1D)

(4, 1) (5, 3) (2, 1)

In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
# first point
float(points[0]), float(points[1])

(4.0, 1.0)

Interesante de hacer con un tensor de 2D    

In [10]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
# first point
points[0]

tensor([4., 1.])

### Indexing tensors

In [13]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [14]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [15]:
points[1:, 0]

tensor([5., 2.])

In [16]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

### Named tensors
Ejemplo imágenes

In [17]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns] -> RGB image with 5x5 pixels
weights = torch.tensor([0.2126, 0.7152, 0.0722]) # weights for RGB to grayscale conversion
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns] -> batch of 2 RGB images with 5x5 pixels
img_t.shape, batch_t.shape

(torch.Size([3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [18]:
# from RGB to grayscale using weighted sum
# RGB is always the last dimension (-3)
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [19]:
img_t, batch_t

(tensor([[[-0.4408,  0.2189, -0.4220,  0.4569,  0.6775],
          [-2.0922, -0.5141, -0.7612,  0.4352, -0.9144],
          [-1.1744,  0.8846, -0.1359,  0.0881,  0.8794],
          [ 0.3326, -0.9234,  1.3971, -1.5118,  0.8071],
          [-0.5000,  0.5624,  0.6304,  2.1964, -0.7936]],
 
         [[ 1.4265,  0.5599, -0.8689, -0.0714,  0.2058],
          [ 0.3003, -1.5945, -0.5612,  0.3705,  0.1867],
          [-0.8969, -1.3450, -0.6095, -0.5716,  1.2077],
          [-0.3709,  1.1745, -0.2929, -1.9076, -0.3852],
          [-2.0868, -0.5904, -1.6871, -1.3191,  1.0512]],
 
         [[ 0.2837, -0.4278, -0.9644, -0.6081, -0.9138],
          [-0.9823,  0.8836, -0.5623, -0.2616,  1.0520],
          [ 0.4948,  0.9902, -1.2033, -0.6398, -0.0461],
          [ 0.1580, -0.6031,  0.5040,  0.2700, -0.3162],
          [-0.0889, -0.3476,  2.4199, -0.4489, -0.8591]]]),
 tensor([[[[ 0.9517,  1.8781, -0.8973, -2.0050, -0.5088],
           [-0.6027, -0.1771,  0.5113, -0.4960,  0.1960],
           [ 1.0571,

In [20]:
img_gray_naive, batch_gray_naive

(tensor([[ 0.4231,  0.1170, -0.7517, -0.0742, -0.0102],
         [-0.9247, -0.4083, -0.6282,  0.1814,  0.1081],
         [-0.5255,  0.1766, -0.6495, -0.3744,  0.6803],
         [ 0.0399, -0.1173,  0.5361, -1.0498,  0.0353],
         [-0.8919, -0.1252,  0.4544,  0.1428, -0.2005]]),
 tensor([[[-0.4406,  1.1408, -0.5642, -0.6002,  0.2773],
          [-0.7034,  0.3715,  0.7678,  0.0922,  0.9075],
          [ 1.0793, -0.1084, -0.1563,  1.0395,  0.2534],
          [ 0.1748, -0.1724,  1.0567, -0.4988,  0.2421],
          [ 0.7087, -0.3442, -0.3089,  0.6281, -0.5323]],
 
         [[-0.2419, -0.5450, -0.0196, -0.5014,  0.2628],
          [-0.9527, -0.4912, -0.7659,  0.4175,  0.4015],
          [-1.3448,  0.7479, -0.8295,  0.4817, -0.3164],
          [-0.2153, -0.0115, -0.7429, -0.1287, -0.4949],
          [-0.2646, -0.9087, -0.6947, -0.2087,  0.5357]]]))

In [21]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1) # add two dimensions at the end
weights, unsqueezed_weights, weights.shape, unsqueezed_weights.shape

(tensor([0.2126, 0.7152, 0.0722]),
 tensor([[[0.2126]],
 
         [[0.7152]],
 
         [[0.0722]]]),
 torch.Size([3]),
 torch.Size([3, 1, 1]))

In [22]:
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
img_gray_weighted.shape, batch_gray_weighted.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

_einsum_

In [23]:
img_gray_weighted_fancy = torch.einsum("...chw,c->...hw", img_t, weights)
batch_gray_weighted_fancy = torch.einsum("...chw,c->...hw", batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

Nombrando dimensiones

In [38]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
weights_named.shape, weights_named.names

(torch.Size([3]), ('channels',))

In [39]:
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
print(f"img named: {img_named.shape}, {img_named.names}")
print(f"batch named: {batch_named.shape}, {batch_named.names}")

img named: torch.Size([3, 5, 5]), ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]), (None, 'channels', 'rows', 'columns')


_align_as_

In [45]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [ ]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named.shape, gray_named.names

tensor([[ 0.9470,  0.4161, -0.7808,  0.0021,  0.2253],
        [-0.3010, -1.1859, -0.6038,  0.3386,  0.0150],
        [-0.8554, -0.7024, -0.5517, -0.4362,  1.0474],
        [-0.1831,  0.6001,  0.1239, -1.6662, -0.1267],
        [-1.6052, -0.3278, -0.8979, -0.5089,  0.5211]],
       names=('rows', 'columns'))

In [50]:
# gray_named = (img_named[..., :3] * weights_named).sum("channels")

In [51]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

### Tensor element types

float32 by default

interesante float16 para GPU, pero no soportado en CPU

índices -> int64

In [57]:
default_points = torch.zeros(10, 2)
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
default_points.dtype, double_points.dtype, short_points.dtype

(torch.float32, torch.float64, torch.int16)

In [53]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [56]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(torch.short)
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

### Tensor API

In [64]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [65]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### Scenic views of storage

In [68]:
torch.Storage

torch.FloatStorage

In [71]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [73]:
points_storage = points.storage()
points_storage[0], points_storage[1]

(4.0, 1.0)

In [74]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [77]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

_Size_, _offset_ and _stride_

In [92]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
print(f"Size: {points.size()}, Offset: {points.storage_offset()}, Stride: {points.stride()}")
print(f"Size: {second_point.size()}, Offset: {second_point.storage_offset()}, Stride: {second_point.stride()}")

Size: torch.Size([3, 2]), Offset: 0, Stride: (2, 1)
Size: torch.Size([2]), Offset: 2, Stride: (1,)


In [93]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [94]:
second_point.storage_offset()

2

In [95]:
second_point.stride()

(1,)

Hacer cambios sobre un "subtensor" proveniente de otro implica que los cambios también se hagan sobre el tensor original

In [96]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

Cuando no se desee que esto suceda se deben crear nuevos tensores

In [97]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Transponer sin copiar

In [117]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [118]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

Ambos tensores comparten el mismo _storage_ (?)

In [120]:
id(points.storage()) == id(points_t.storage())

False

In [121]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [127]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()

print("id(storage):", id(points.storage()), id(points_t.storage()))
print("data_ptr:", points.data_ptr(), points_t.data_ptr())
print("comparten memoria (data_ptr equal)?", points.data_ptr() == points_t.data_ptr())
print("storage_offset:", points.storage_offset(), points_t.storage_offset())
print("stride:", points.stride(), points_t.stride())

id(storage): 139706507392928 139710475142992
data_ptr: 94630579371200 94630579371200
comparten memoria (data_ptr equal)? True
storage_offset: 0 0
stride: (2, 1) (1, 2)


Transposición con mayores dimensiones

In [126]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
print(f"{some_t.shape}, {transpose_t.shape}")
print(f"{some_t.stride()}, {transpose_t.stride()}")

torch.Size([3, 4, 5]), torch.Size([5, 4, 3])
(20, 5, 1), (1, 5, 20)


Tensores contiguos

In [128]:
points.is_contiguous()

True

In [129]:
points_t.is_contiguous()

False

In [130]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [131]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [132]:
points_t.stride()

(1, 2)

In [133]:
points_t.is_contiguous()

False

In [134]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [135]:
points_t_cont.stride()

(3, 1)

In [136]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [137]:
points_t_cont.is_contiguous()

True

### Tensores en GPU

Creación de un tensor directamente en GPU

In [138]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

Copiar un tensor de CPU a GPU

In [139]:
points_gpu = points.to(device='cuda')

In [140]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')

In [145]:
# measure times cpu vs gpu
import time
def measure_matrix_mult(size, device):
    a = torch.randn(size, device=device)
    b = torch.randn(size, device=device)
    start_time = time.time()
    a @ b
    end_time = time.time()
    return end_time - start_time

size = (10000, 10000)
cpu_time = measure_matrix_mult(size, device='cpu')
print(f"CPU time: {cpu_time:.6f} seconds")
gpu_time = measure_matrix_mult(size, device='cuda')
print(f"GPU time: {gpu_time:.6f} seconds")

CPU time: 4.371414 seconds
GPU time: 0.000089 seconds


Serializando tensores

In [ ]:
torch.save(points, "data/ourpoints.t")
points = torch.load("data/ourpoints.t")

In [ ]:
with open("data/ourpoints.t", "wb") as f:
    torch.save(points, f)   

with open("data/ourpoints.t", "rb") as f:
    points = torch.load(f)

HDF5 -- h5py

In [149]:
import h5py
f = h5py.File("data/ourpoints.hdf5", "w")
dset = f.create_dataset("coords", data=points.numpy())
f.close()

In [150]:
f = h5py.File("data/ourpoints.hdf5", "r")
dset = f["coords"]
last_points = dset[-2:]

In [151]:
last_points = torch.from_numpy(dset[-2:])
f.close()

Exercises

In [167]:
a = list(range(9))
t = torch.tensor(a)
b = t.view(3, 3)
print(f"{a}\n{t}\n{b}")

c = b[1:, 1:]
print(f"{c}\n{c.shape}\n{c.storage_offset()}\n{c.stride()}")

[0, 1, 2, 3, 4, 5, 6, 7, 8]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2])
4
(3, 1)


In [172]:
d = torch.cos(t)
torch.cos_(d)
e = torch.sqrt(d)
torch.sqrt_(e)
print(f"{d}\n{e}")

tensor([0.5403, 0.8576, 0.9147, 0.5487, 0.7939, 0.9600, 0.5734, 0.7290, 0.9894])
tensor([0.8574, 0.9623, 0.9779, 0.8607, 0.9439, 0.9899, 0.8702, 0.9240, 0.9973])
